export const FALLBACK_CATEGORIES = [
    { id: 'measuring_instruments', label: 'Measuring Instruments' },
    { id: 'sporting_goods', label: 'Sporting Goods' },
    { id: 'automotive_parts', label: 'Automotive Parts' },
    { id: 'hvac_systems', label: 'HVAC Systems & Components' },
    { id: 'mining_equipment', label: 'Mining Equipment' },
    { id: 'semiconductor_electronics', label: 'Semiconductor & Electronics Components' },
    { id: 'apparel_textiles', label: 'Apparel & Textiles' },
    { id: 'plastics_polymers', label: 'Plastics & Polymers' },
    { id: 'printing_machinery', label: 'Printing Machinery' },
    { id: 'cnc_metalworking', label: 'CNC & Metalworking Machines' },
    { id: 'chemicals_raw_materials', label: 'Chemicals & Raw Materials' },
    { id: 'material_handling', label: 'Material Handling Equipment' },
    { id: 'batteries_energy_storage', label: 'Batteries & Energy Storage' },
    { id: 'textile_machinery', label: 'Textile Machinery' },
    { id: 'home_kitchen', label: 'Home & Kitchen' },
    { id: 'consumer_electronics', label: 'Consumer Electronics' },
    { id: 'industrial_safety', label: 'Industrial Safety Equipment' },
    { id: 'food_beverages', label: 'Food & Beverages' },
    { id: 'medical_equipment', label: 'Medical Equipment' },
    { id: 'electronics_gadgets', label: 'Electronics & Gadgets' },
    { id: 'paints_coatings', label: 'Paints & Coatings' },
    { id: 'power_generation', label: 'Power Generation Equipment' },
    { id: 'renewable_energy', label: 'Renewable Energy Equipment' },
    { id: 'glass_ceramics', label: 'Glass & Ceramics' },
    { id: 'pipes_valves_fittings', label: 'Pipes, Valves & Fittings' },
    { id: 'industrial_automation_robotics', label: 'Industrial Automation & Robotics' },
    { id: 'packaging_machinery', label: 'Packaging Machinery' },
    { id: 'plumbing_sanitary', label: 'Plumbing & Sanitary Equipment' },
    { id: 'health_personal_care', label: 'Health & Personal Care' },
    { id: 'wire_cable', label: 'Wire & Cable Products' },
    { id: 'lighting_fixtures', label: 'Lighting & Fixtures' },
    { id: 'solar_panels_components', label: 'Solar Panels & Components' },
    { id: 'machinery_tools', label: 'Machinery & Tools' },
    { id: 'agriculture_farming', label: 'Agriculture & Farming' },
    { id: 'metal_alloys', label: 'Metals & Alloys' },
    { id: 'leather_goods', label: 'Leather Goods' },
    { id: 'construction_machinery', label: 'Construction Machinery' },
    { id: 'wood_products', label: 'Wood & Wood Products' },
    { id: 'furniture_interiors', label: 'Furniture & Interiors' },
    { id: 'industrial_refrigeration_cooling', label: 'Industrial Refrigeration & Cooling' },
    { id: 'beverage_manufacturing_equipment', label: 'Beverage Manufacturing Equipment' },
    { id: 'paper_pulp_products', label: 'Paper & Pulp Products' },
    { id: 'construction_materials', label: 'Construction Materials' },
    { id: 'ev_charging_infrastructure', label: 'EV Charging Infrastructure' },
    { id: 'industrial_furnaces_kilns', label: 'Industrial Furnaces & Kilns' },
    { id: 'pumps_compressors', label: 'Pumps & Compressors' },
    { id: 'textile_fabrics', label: 'Textile Fabrics' },
    { id: 'bearings_mechanical_parts', label: 'Bearings & Mechanical Parts' },
    { id: 'threed_printing_additive', label: '3D Printing & Additive Manufacturing' },
    { id: 'transformers_switchgear', label: 'Transformers & Switchgear' },
    { id: 'footwear', label: 'Footwear' },
    { id: 'jewelry_accessories', label: 'Jewelry & Accessories' },
    { id: 'fasteners_hardware', label: 'Fasteners & Hardware' },
    { id: 'toys_sports_equipment', label: 'Toys & Sports Equipment' },
    { id: 'food_processing_machinery', label: 'Food Processing Machinery' },
    { id: 'electrical_equipment', label: 'Electrical Equipment' },
    { id: 'packaging_printing', label: 'Packaging & Printing' },
    { id: 'industrial_boilers_steam', label: 'Industrial Boilers & Steam Systems' },
    { id: 'adhesives_sealants', label: 'Adhesives & Sealants' },
    { id: 'leather_processing_equipment', label: 'Leather Processing Equipment' },
    { id: 'rubber_products', label: 'Rubber Products' },
    { id: 'paper_pulp_packaging_materials', label: 'Paper, Pulp & Packaging Materials' },
    { id: 'industrial_lubricants_oils', label: 'Industrial Lubricants & Oils' },
    { id: 'industrial_automation', label: 'Industrial Automation' },
    { id: 'other', label: 'Other' },
];
