export const FALLBACK_CATEGORIES = [
    { id: 'measuring_instruments', label: 'Measuring Instruments' },
    { id: 'sporting_goods', label: 'Sporting Goods' },
    { id: 'automotive_parts', label: 'Automotive Parts' },
    { id: 'hvac_systems', label: 'HVAC Systems & Components' },
    { id: 'mining_equipment', label: 'Mining Equipment' },
    { id: 'semiconductor_electronics', label: 'Semiconductor & Electronics Components' },
    { id: 'apparel_textiles', label: 'Apparel & Textiles' },
    { id: 'plastics_polymers', label: 'Plastics & Polymers' },
    { id: 'printing_machinery', label: 'Printing Machinery' },
    { id: 'cnc_metalworking', label: 'CNC & Metalworking Machines' },
    { id: 'chemicals_raw_materials', label: 'Chemicals & Raw Materials' },
    { id: 'material_handling', label: 'Material Handling Equipment' },
    { id: 'batteries_energy_storage', label: 'Batteries & Energy Storage' },
    { id: 'textile_machinery', label: 'Textile Machinery' },
    { id: 'home_kitchen', label: 'Home & Kitchen' },
    { id: 'consumer_electronics', label: 'Consumer Electronics' },
    { id: 'industrial_safety', label: 'Industrial Safety Equipment' },
    { id: 'food_beverages', label: 'Food & Beverages' },
    { id: 'medical_equipment', label: 'Medical Equipment' },
    { id: 'electronics_gadgets', label: 'Electronics & Gadgets' },
    { id: 'paints_coatings', label: 'Paints & Coatings' },
    { id: 'power_generation', label: 'Power Generation Equipment' },
    { id: 'renewable_energy', label: 'Renewable Energy Equipment' },
    { id: 'glass_ceramics', label: 'Glass & Ceramics' },
    { id: 'pipes_valves_fittings', label: 'Pipes, Valves & Fittings' },
    { id: 'industrial_automation_robotics', label: 'Industrial Automation & Robotics' },
    { id: 'packaging_machinery', label: 'Packaging Machinery' },
    { id: 'plumbing_sanitary', label: 'Plumbing & Sanitary Equipment' },
    { id: 'health_personal_care', label: 'Health & Personal Care' },
    { id: 'wire_cable', label: 'Wire & Cable Products' },
    { id: 'lighting_fixtures', label: 'Lighting & Fixtures' },
    { id: 'solar_panels_components', label: 'Solar Panels & Components' },
    { id: 'machinery_tools', label: 'Machinery & Tools' },
    { id: 'agriculture_farming', label: 'Agriculture & Farming' },
    { id: 'metal_alloys', label: 'Metals & Alloys' },
    { id: 'leather_goods', label: 'Leather Goods' },
    { id: 'construction_machinery', label: 'Construction Machinery' },
    { id: 'wood_products', label: 'Wood & Wood Products' },
    { id: 'furniture_interiors', label: 'Furniture & Interiors' },
    { id: 'industrial_refrigeration_cooling', label: 'Industrial Refrigeration & Cooling' },
    { id: 'beverage_manufacturing_equipment', label: 'Beverage Manufacturing Equipment' },
    { id: 'paper_pulp_products', label: 'Paper & Pulp Products' },
    { id: 'construction_materials', label: 'Construction Materials' },
    { id: 'ev_charging_infrastructure', label: 'EV Charging Infrastructure' },
    { id: 'industrial_furnaces_kilns', label: 'Industrial Furnaces & Kilns' },
    { id: 'pumps_compressors', label: 'Pumps & Compressors' },
    { id: 'textile_fabrics', label: 'Textile Fabrics' },
    { id: 'bearings_mechanical_parts', label: 'Bearings & Mechanical Parts' },
    { id: 'threed_printing_additive', label: '3D Printing & Additive Manufacturing' },
    { id: 'transformers_switchgear', label: 'Transformers & Switchgear' },
    { id: 'footwear', label: 'Footwear' },
    { id: 'jewelry_accessories', label: 'Jewelry & Accessories' },
    { id: 'fasteners_hardware', label: 'Fasteners & Hardware' },
    { id: 'toys_sports_equipment', label: 'Toys & Sports Equipment' },
    { id: 'food_processing_machinery', label: 'Food Processing Machinery' },
    { id: 'electrical_equipment', label: 'Electrical Equipment' },
    { id: 'packaging_printing', label: 'Packaging & Printing' },
    { id: 'industrial_boilers_steam', label: 'Industrial Boilers & Steam Systems' },
    { id: 'adhesives_sealants', label: 'Adhesives & Sealants' },
    { id: 'leather_processing_equipment', label: 'Leather Processing Equipment' },
    { id: 'rubber_products', label: 'Rubber Products' },
    { id: 'paper_pulp_packaging_materials', label: 'Paper, Pulp & Packaging Materials' },
    { id: 'industrial_lubricants_oils', label: 'Industrial Lubricants & Oils' },
    { id: 'industrial_automation', label: 'Industrial Automation' },
    { id: 'aerospace_components_manufacturing', label: 'Aerospace Components Manufacturing' },
    { id: 'audio_equipment_manufacturing', label: 'Audio Equipment Manufacturing' },
    { id: 'automation_control_devices', label: 'Automation Control Devices' },
    { id: 'battery_packs_manufacturing', label: 'Battery Packs Manufacturing' },
    { id: 'blow_molding_products', label: 'Blow Molding Products' },
    { id: 'broadcast_equipment_manufacturing', label: 'Broadcast Equipment Manufacturing' },
    { id: 'casting_foundry_products', label: 'Casting & Foundry Products' },
    { id: 'computer_server_manufacturing', label: 'Computer & Server Manufacturing' },
    { id: 'consumer_electronics_assembly', label: 'Consumer Electronics Assembly' },
    { id: 'control_panels_manufacturing', label: 'Control Panels Manufacturing' },
    { id: 'cutting_tools_manufacturing', label: 'Cutting Tools Manufacturing' },
    { id: 'defense_equipment_manufacturing', label: 'Defense Equipment Manufacturing' },
    { id: 'ev_components_manufacturing', label: 'EV Components Manufacturing' },
    { id: 'electric_motors_manufacturing', label: 'Electric Motors Manufacturing' },
    { id: 'electrical_panels_manufacturing', label: 'Electrical Panels Manufacturing' },
    { id: 'flexible_packaging_products', label: 'Flexible Packaging Products' },
    { id: 'foam_sponge_products', label: 'Foam & Sponge Products' },
    { id: 'forging_products_manufacturing', label: 'Forging Products Manufacturing' },
    { id: 'gaskets_seals_manufacturing', label: 'Gaskets & Seals Manufacturing' },
    { id: 'hand_tools_manufacturing', label: 'Hand Tools Manufacturing' },
    { id: 'heat_treatment_services', label: 'Heat Treatment Services' },
    { id: 'heavy_fabrication', label: 'Heavy Fabrication' },
    { id: 'it_hardware_manufacturing', label: 'IT Hardware Manufacturing' },
    { id: 'industrial_gas_manufacturing', label: 'Industrial Gas Manufacturing' },
    { id: 'industrial_packaging_products', label: 'Industrial Packaging Products' },
    { id: 'industrial_sensors_manufacturing', label: 'Industrial Sensors Manufacturing' },
    { id: 'industrial_storage_systems', label: 'Industrial Storage Systems' },
    { id: 'industrial_tools_manufacturing', label: 'Industrial Tools Manufacturing' },
    { id: 'iot_devices_manufacturing', label: 'IoT Devices Manufacturing' },
    { id: 'lubricants_grease_manufacturing', label: 'Lubricants & Grease Manufacturing' },
    { id: 'marine_ship_equipment_manufacturing', label: 'Marine & Ship Equipment Manufacturing' },
    { id: 'micro_components_manufacturing', label: 'Micro Components Manufacturing' },
    { id: 'modular_furniture_manufacturing', label: 'Modular Furniture Manufacturing' },
    { id: 'networking_equipment_manufacturing', label: 'Networking Equipment Manufacturing' },
    { id: 'office_furniture_manufacturing', label: 'Office Furniture Manufacturing' },
    { id: 'plastic_injection_molding', label: 'Plastic Injection Molding' },
    { id: 'power_distribution_equipment', label: 'Power Distribution Equipment' },
    { id: 'power_electronics_manufacturing', label: 'Power Electronics Manufacturing' },
    { id: 'precision_components_manufacturing', label: 'Precision Components Manufacturing' },
    { id: 'protective_packaging_manufacturing', label: 'Protective Packaging Manufacturing' },
    { id: 'rotational_molding_products', label: 'Rotational Molding Products' },
    { id: 'rubber_molding_products', label: 'Rubber Molding Products' },
    { id: 'semiconductor_electronic_components', label: 'Semiconductor & Electronic Components' },
    { id: 'sheet_metal_fabrication', label: 'Sheet Metal Fabrication' },
    { id: 'smart_devices_manufacturing', label: 'Smart Devices Manufacturing' },
    { id: 'specialty_chemical_manufacturing', label: 'Specialty Chemical Manufacturing' },
    { id: 'studio_equipment_manufacturing', label: 'Studio Equipment Manufacturing' },
    { id: 'telecom_equipment_manufacturing', label: 'Telecom Equipment Manufacturing' },
    { id: 'thermoforming_products', label: 'Thermoforming Products' },
    { id: 'video_production_equipment', label: 'Video Production Equipment' },
    { id: 'wearable_devices_manufacturing', label: 'Wearable Devices Manufacturing' },
    { id: 'other', label: 'Other' },
];
